import Link from 'next/link'
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from '@/components/ui/hover-card'
import { buttonVariants } from '@/components/ui/button'

export const ModelHoverCard = ({ model }: { model: string }) => {
  return (
    <HoverCard>
      <HoverCardTrigger>
        {' '}
        <button className="font-mono not-italic bg-fuchsia-100 px-2 py-1 rounded-md">
          🤖 {model}
        </button>
      </HoverCardTrigger>
      <HoverCardContent>
        <p>
          The <strong>language</strong>, <strong>politics</strong>, and{' '}
          <strong>analysis</strong> fields on this page were all AI-generated by
          this model.
        </p>
        <Link
          className={`${buttonVariants({
            variant: 'link',
            size: 'sm',
          })} text-xs !px-0`}
          href="/about"
        >
          Read more &rarr;
        </Link>
      </HoverCardContent>
    </HoverCard>
  )
}
